# Generated by Django 3.2 on 2021-12-06 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_chat', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Chat',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Estudiante'), ('2', 'Docente')], default=1, max_length=1)),
                ('imagen', models.ImageField(null=True, upload_to='users/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_cuenta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cuenta',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=60)),
                ('cuentas', models.ManyToManyField(related_name='cursos_inscritos', to='PortAll50.Cuenta')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_creados', to='PortAll50.cuenta')),
            ],
            options={
                'verbose_name_plural': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_foro', models.CharField(max_length=60)),
                ('asignacion_foro', models.CharField(max_length=300)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foros', to='PortAll50.curso')),
            ],
            options={
                'verbose_name_plural': 'Foro',
            },
        ),
        migrations.CreateModel(
            name='RespuestaForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesa_foro', models.CharField(max_length=1000)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='PortAll50.cuenta')),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='PortAll50.foro')),
            ],
            options={
                'verbose_name_plural': 'RespuestasForo',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=100)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='PortAll50.chat')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='PortAll50.cuenta')),
            ],
            options={
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_material', models.CharField(max_length=60)),
                ('archivo', models.FileField(blank=True, upload_to='materiales/')),
                ('enlace', models.URLField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='PortAll50.curso')),
            ],
            options={
                'verbose_name_plural': 'Material',
            },
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entregable', models.CharField(max_length=30)),
                ('archivo', models.FileField(blank=True, upload_to='entregables/')),
                ('comentario', models.CharField(max_length=100)),
                ('tiempo_disp_desde', models.DateTimeField()),
                ('tiempo_disp_hasta', models.DateTimeField()),
                ('tiempo_ver_desde', models.DateTimeField()),
                ('tiempo_ver_para', models.DateTimeField()),
                ('estado_entrega', models.CharField(choices=[('0', 'Colocada'), ('1', 'Mostrar'), ('2', 'Recibida')], default='0', max_length=1)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='PortAll50.curso')),
            ],
            options={
                'verbose_name_plural': 'Entregable',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_entrega', models.FileField(blank=True, upload_to='entregas/%Y/%m/%d')),
                ('tiempo_entregado', models.DateTimeField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='PortAll50.cuenta')),
                ('entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='PortAll50.entregable')),
            ],
            options={
                'verbose_name_plural': 'Entrega',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='PortAll50.curso'),
        ),
    ]
