# Generated by Django 3.2 on 2021-12-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cuentas',
            field=models.ManyToManyField(null=True, related_name='cursos_inscritos', to='PortAll50.Cuenta'),
        ),
    ]
