# Generated by Django 3.2 on 2021-12-07 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0003_alter_curso_propietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='propietario',
        ),
    ]
