# Generated by Django 3.2 on 2021-12-07 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PortAll50', '0005_curso_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_creados', to='auth.user'),
        ),
    ]
