# Generated by Django 3.2 on 2021-12-07 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PortAll50', '0008_alter_cuenta_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cuentas',
            field=models.ManyToManyField(null=True, related_name='cursos_inscritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
