# Generated by Django 3.2 on 2021-12-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0011_auto_20211208_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='estado_entrega',
            field=models.CharField(choices=[('1', 'Mostrar'), ('2', 'Recibida')], default='1', max_length=1),
        ),
    ]
