# Generated by Django 3.2 on 2021-12-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0012_alter_entregable_estado_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
