# Generated by Django 3.2 on 2021-12-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0013_alter_entregable_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='tiempo_entregado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
