# Generated by Django 3.2 on 2021-12-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0014_alter_entrega_tiempo_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
