# Generated by Django 3.2 on 2021-12-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0015_alter_entrega_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='tiempo_disp_hasta',
            field=models.DateTimeField(null=True),
        ),
    ]
