# Generated by Django 3.2 on 2021-12-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0016_entregable_tiempo_disp_hasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaforo',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
