# Generated by Django 3.2 on 2021-12-09 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PortAll50', '0017_alter_respuestaforo_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaforo',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to=settings.AUTH_USER_MODEL),
        ),
    ]
