# Generated by Django 3.2 on 2021-12-09 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0018_alter_respuestaforo_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaforo',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='PortAll50.cuenta'),
        ),
    ]
