# Generated by Django 3.2 on 2021-12-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0019_alter_respuestaforo_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregable',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='material',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='material',
            name='enlace',
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccion_curso', to='PortAll50.curso')),
            ],
            options={
                'verbose_name_plural': 'Seccion',
            },
        ),
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_enlace', models.CharField(max_length=60)),
                ('enlace', models.URLField()),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccion_enlace', to='PortAll50.seccion')),
            ],
            options={
                'verbose_name_plural': 'Enlace',
            },
        ),
        migrations.AddField(
            model_name='entregable',
            name='seccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seccion_entregable', to='PortAll50.seccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foro',
            name='seccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seccion_foro', to='PortAll50.seccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='seccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seccion_material', to='PortAll50.seccion'),
            preserve_default=False,
        ),
    ]
