# Generated by Django 3.2 on 2021-12-10 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PortAll50', '0020_auto_20211209_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL),
        ),
    ]
