# Generated by Django 3.2 on 2021-12-11 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0022_entrega_estado_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_enlace', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccion_url', to='PortAll50.seccion')),
            ],
            options={
                'verbose_name_plural': 'Url',
            },
        ),
    ]
