# Generated by Django 3.2 on 2021-12-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0024_rename_curso_url_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cantidad_minima',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='estado_curso',
            field=models.CharField(choices=[('0', 'Preparando'), ('1', 'Activo'), ('2', 'Finalizo')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='curso',
            name='total_acumular',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
