# Generated by Django 3.2 on 2021-12-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0025_auto_20211213_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='actual_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='foro',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
