# Generated by Django 3.2 on 2021-12-14 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0026_auto_20211213_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='PortAll50.curso'),
        ),
    ]
