# Generated by Django 3.2 on 2021-12-14 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0027_alter_chat_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='curso',
        ),
    ]
