# Generated by Django 3.2 on 2021-12-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0029_chat_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='estado_entrega',
            field=models.CharField(choices=[('0', 'Sin calificar'), ('1', 'Calificado')], default='0', max_length=1),
        ),
    ]
