# Generated by Django 3.2 on 2021-12-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0031_nota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
