# Generated by Django 3.2 on 2021-12-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PortAll50', '0033_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_curso', to='PortAll50.curso'),
        ),
    ]
