# Generated by Django 3.2 on 2021-12-16 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PortAll50', '0034_alter_nota_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='cuenta',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='auth.user'),
            preserve_default=False,
        ),
    ]
